from __future__ import annotations

import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INDEX_HTML = ROOT / "index.html"
SETTINGS_HTML = ROOT / "settings.html"
SETTINGS_JS = ROOT / "settings.js"


class ChatModesUiTests(unittest.TestCase):
    def test_index_contains_chat_mode_buttons_and_payload(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        self.assertIn('data-chat-mode="react"', source)
        self.assertIn('data-chat-mode="chat"', source)
        self.assertIn('data-chat-mode="skill"', source)
        self.assertIn("chat_mode: currentChatMode", source)
        self.assertIn('model: state.chat.model || "hermes-agent"', source)
        self.assertNotIn("router_enabled: !!state.chat.router_enabled", source)
        self.assertNotIn('router_model: state.chat.router_model || ""', source)

    def test_index_contains_sidebar_buttons_in_new_order(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        settings_pos = source.find("<span>设置</span>")
        history_pos = source.find("<span>历史</span>")
        new_chat_pos = source.find("<span>新对话</span>")
        self.assertNotEqual(settings_pos, -1)
        self.assertNotEqual(history_pos, -1)
        self.assertNotEqual(new_chat_pos, -1)
        self.assertLess(settings_pos, history_pos)
        self.assertLess(history_pos, new_chat_pos)
        self.assertIn('id="nav-history"', source)
        self.assertIn('id="nav-chat"', source)

    def test_index_contains_topic_history_ui_and_api_hooks(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        self.assertIn('id="chat-history-drawer"', source)
        self.assertIn('id="chat-history-list"', source)
        self.assertIn('id="chat-history-refresh"', source)
        self.assertIn('/api/chat/topics', source)
        self.assertIn('async function createNewTopic', source)
        self.assertIn('async function loadTopicHistory', source)
        self.assertIn('async function selectTopic', source)
        self.assertIn('async function deleteTopic', source)
        self.assertIn('chat-history-delete', source)
        self.assertIn('pendingDeleteTopicId', source)
        self.assertIn('armPendingDeleteTopic', source)
        self.assertIn('clearPendingDeleteTopic', source)
        self.assertIn('\u786e\u8ba4\u5220\u9664', source)
        self.assertIn('chat-history-delete.is-danger', source)
        self.assertIn('deleteButton.textContent = isPendingDelete ? "\\u786e\\u8ba4\\u5220\\u9664" : "\\u5220\\u9664"', source)
        self.assertIn('deleteButton.setAttribute("aria-label", isPendingDelete ? "\\u786e\\u8ba4\\u5220\\u9664\\u8bdd\\u9898" : "\\u5220\\u9664\\u8bdd\\u9898")', source)
        self.assertNotIn('window.confirm', source)
        self.assertIn('method: "DELETE"', source)
        self.assertIn('/delete', source)
        self.assertIn('Array.isArray(payload.topics)', source)
        self.assertNotIn('405\\uff08\\u65b9\\u6cd5\\u4e0d\\u5141\\u8bb8\\uff09', source)
        self.assertIn('topic_id', source)
        self.assertIn('chat-asr-status', source)
        self.assertIn('function canStartPushToTalk', source)
        self.assertIn('startPushToTalk', source)
        self.assertIn('/api/asr/stream', source)
        self.assertIn('/api/health', source)
        self.assertIn('/api/asr/warmup', source)
        self.assertIn('state.chat?.asr?.api_base_url', source)
        self.assertIn('function candidateAsrBaseUrls()', source)
        self.assertIn('function buildAsrWarmupUrl(baseUrl = "")', source)
        self.assertIn('callQtBridge("startAsrWarmup")', source)
        self.assertIn('function isProbablyMacOS()', source)
        self.assertIn('[macOS] ASR 默认关闭，聊天仍可用', source)
        self.assertIn('function shouldRetryAsrAvailability(message)', source)
        self.assertIn('String(state.chat?.backend_url || "").trim()', source)
        self.assertIn('let sawSocketError = false;', source)
        self.assertIn('let lastSocketErrorMessage = "";', source)
        self.assertIn('lastSocketErrorMessage || (sawSocketError ? "ASR WebSocket 连接错误" : "ASR 连接已关闭")', source)
        self.assertIn('while (token === asrRunToken && asrHotkeyPressed && !availability.ok) {', source)

    def test_index_tracks_thought_sessions_per_turn_boundary(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        self.assertIn('let activeThoughtSessionId = "";', source)
        self.assertIn('const approvalThoughtSessionRefs = new Map();', source)
        self.assertNotIn('const memorySuggestionRefs = new Map();', source)
        self.assertIn("function createThoughtSessionId()", source)
        self.assertIn("function beginThoughtSession(existingSessionId = \"\")", source)
        self.assertIn("function clearActiveThoughtSession(sessionId = \"\")", source)
        self.assertIn("function ensureThoughtGroup(round = 1, pending = false, sessionId = \"\")", source)
        self.assertIn("currentThoughtGroup.sessionId === normalizedSessionId", source)
        self.assertIn("const thoughtSessionId = beginThoughtSession();", source)
        self.assertIn("approvalThoughtSessionRefs.get(turnKey)", source)
        self.assertIn("await consumeChatStream(resp, { thoughtSessionId })", source)
        self.assertIn("clearActiveThoughtSession(thoughtSessionId);", source)

    def test_index_supports_searcher_role_and_step_batch_meta(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        self.assertIn('value === "searcher"', source)
        self.assertIn("function formatStepMeta(payload)", source)
        self.assertIn("步骤 ${stepIndex}", source)
        self.assertIn("批次：${batchSize} 次工具调用", source)
        self.assertIn("const metaText = formatStepMeta(payload);", source)
        self.assertNotIn('memory_save_suggestion', source)
        self.assertNotIn('/api/chat/memory/decision', source)

    def test_index_requests_tts_once_after_stream_finishes(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        self.assertIn("function feedSpeakBuffer(delta, force = false, expr = null)", source)
        self.assertIn("if (!force) {\n          return;\n        }", source)
        self.assertIn('feedSpeakBuffer("", true);', source)
        self.assertNotIn("pendingSpeakBuffer.match", source)
        self.assertNotIn("await fallbackSpeakByBrowser(nextText)", source)

    def test_index_respects_runtime_topic_history_capabilities(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        self.assertIn("supports_history_detail: raw.supports_history_detail !== false", source)
        self.assertIn("supports_delete: raw.supports_delete !== false", source)
        self.assertIn("if (item.supports_delete) {", source)
        self.assertIn("if (payload.history_unavailable) {", source)
        self.assertIn("if (!resp.ok || payload.ok === false) {", source)
        self.assertNotIn("该话题由 AstrBot 管理，当前请在 AstrBot WebUI 删除。", source)
        self.assertNotIn("AstrBot 当前只开放会话列表；历史明细请在 AstrBot WebUI 查看。", source)

    def test_index_contains_codex_worklog_rendering_functions(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        self.assertIn("function ensureAssistantWorklogTurn", source)
        self.assertIn("function appendWorklogPhase", source)
        self.assertIn("function updateWorklogFinalText", source)
        self.assertIn("function appendAssistantHistoryBlock", source)
        self.assertIn("assistant-worklog", source)
        self.assertIn("worklog-status-list", source)
        self.assertIn("worklog-final-text", source)

    def test_index_streams_ai_final_output_into_worklog_not_pet_bubble(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        self.assertNotIn('finalMsg = appendMessage("pet"', source)
        self.assertNotIn('appendMessage("pet", text, {\n                  phase,', source)
        self.assertIn("updateWorklogFinalText(ensureAssistantWorklogTurn", source)
        self.assertIn("appendWorklogPhase(payload", source)

    def test_index_user_messages_still_use_bubbles(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        self.assertIn('appendMessage("user", userText, { speakerName: "你" });', source)
        self.assertIn('appendMessage("user", String(item.content || "")', source)

    def test_index_history_assistant_messages_render_without_pet_bubbles(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        self.assertIn("appendAssistantHistoryBlock(item)", source)
        self.assertNotIn('appendMessage(role === "assistant" ? "pet" : "user"', source)

    def test_settings_exposes_topic_history_controls_and_reasoning_input(self) -> None:
        html = SETTINGS_HTML.read_text(encoding="utf-8")
        js = SETTINGS_JS.read_text(encoding="utf-8")
        self.assertNotIn('id="chat-topic-history-enabled"', html)
        self.assertNotIn('id="chat-topic-history-summary-interval"', html)
        self.assertNotIn('id="chat-long-term-memory-enabled"', html)
        self.assertNotIn('id="chat-long-term-memory-project"', html)
        self.assertNotIn('id="chat-long-term-memory-read-enabled"', html)
        self.assertNotIn('id="chat-long-term-memory-ask-before-save"', html)
        self.assertIn('id="chat-asr-enabled"', html)
        self.assertIn('id="chat-asr-push-to-talk-key"', html)
        self.assertIn('id="chat-asr-interim-results"', html)
        self.assertIn('id="vision-enabled"', html)
        self.assertIn('id="vision-capture-interval-ms"', html)
        self.assertIn('id="vision-max-width"', html)
        self.assertIn('id="vision-jpeg-quality"', html)
        self.assertIn('id="vision-context-ttl-sec"', html)
        self.assertIn('id="vision-routing-visual-change-threshold"', html)
        self.assertIn('id="vision-routing-vlm-cooldown-sec"', html)
        self.assertIn('id="vision-routing-stable-after-change-ms"', html)
        self.assertIn('id="vision-inject-policy"', html)
        self.assertIn('id="vision-force-grounding"', html)
        self.assertIn('id="vision-active-observation-enabled"', html)
        self.assertIn('id="vision-active-observation-allowed-interaction"', html)
        self.assertIn('id="vision-active-observation-timeout-sec"', html)
        self.assertIn('id="vision-active-observation-settle-ms"', html)
        self.assertIn('id="vision-passive-capture-use-for-forced"', html)
        self.assertIn('id="vision-analyzer-enabled"', html)
        self.assertIn('id="vision-analyzer-provider"', html)
        self.assertIn('id="vision-analyzer-base-url"', html)
        self.assertIn('id="vision-analyzer-model"', html)
        self.assertIn('id="vision-analyzer-api-key"', html)
        self.assertIn('id="vision-analyzer-api-key-clear"', html)
        self.assertIn('id="vision-analyzer-model-select"', html)
        self.assertIn('id="fetch-vision-analyzer-models-btn"', html)
        self.assertIn('id="apply-vision-analyzer-model-btn"', html)
        self.assertIn('id="vision-analyzer-image-detail"', html)
        self.assertIn('id="vision-analyzer-max-text-chars"', html)
        self.assertIn('id="vision-analyzer-max-observations"', html)
        self.assertIn('id="vision-analyzer-fallback-to-runtime"', html)
        self.assertIn('id="chat-max-reasoning-steps"', html)
        self.assertIn("运行时与语音", html)
        self.assertIn("默认 AstrBot 连接", html)
        self.assertIn('id="hermes-enabled"', html)
        self.assertIn('id="hermes-auto-start"', html)
        self.assertIn('id="hermes-base-url"', html)
        self.assertIn('id="hermes-command"', html)
        self.assertIn('id="hermes-status-detail"', html)
        self.assertIn("/api/hermes/status", js)

    def test_settings_exposes_runtime_and_astrbot_controls(self) -> None:
        html = SETTINGS_HTML.read_text(encoding="utf-8")
        js = SETTINGS_JS.read_text(encoding="utf-8")
        self.assertIn('id="runtime-active-hermes"', html)
        self.assertIn('id="runtime-active-astrbot"', html)
        self.assertIn("AstrBot 保持默认", html)
        self.assertIn('runtime.active || "astrbot"', js)
        self.assertIn('els.runtimeActiveHermes.checked = activeRuntime === "hermes"', js)
        self.assertIn('els.runtimeActiveAstrBot.checked = activeRuntime !== "hermes"', js)
        self.assertIn('active: els.runtimeActiveHermes?.checked ? "hermes" : "astrbot"', js)
        self.assertIn('id="astrbot-base-url"', html)
        self.assertIn('id="astrbot-api-key"', html)
        self.assertIn('id="astrbot-api-key-clear"', html)
        self.assertIn('id="napcatqq-reverse-ws-url"', html)
        self.assertIn("/api/runtime/status", js)
        self.assertIn('api_key_action: astrobotApiKeyAction', js)
        self.assertIn("ws://127.0.0.1:6199/ws", js)
        self.assertIn('id="runtime-main-model-presets"', html)
        self.assertIn('id="runtime-session-presets"', html)
        self.assertNotIn('id="runtime-router-model-presets"', html)
        self.assertNotIn('id="fetch-remote-models-btn"', html)
        self.assertNotIn('id="fetch-router-models-btn"', html)
        self.assertNotIn("拉取模型</button>", html)
        self.assertNotIn('max="12"', html)
        self.assertNotIn('chatTopicHistoryEnabled', js)
        self.assertNotIn('chatTopicHistorySummaryInterval', js)
        self.assertNotIn('chatLongTermMemoryEnabled', js)
        self.assertNotIn('chatLongTermMemoryProject', js)
        self.assertNotIn('chatLongTermMemoryReadEnabled', js)
        self.assertNotIn('chatLongTermMemoryAskBeforeSave', js)
        self.assertIn('chatAsrEnabled', js)
        self.assertIn('chatAsrPushToTalkKey', js)
        self.assertIn('chatAsrInterimResults', js)
        self.assertIn('visionEnabled', js)
        self.assertIn('visionForceGrounding', js)
        self.assertIn('visionActiveObservationEnabled', js)
        self.assertIn('visionActiveObservationInteraction', js)
        self.assertIn('visionPassiveCaptureUseForForced', js)
        self.assertIn('active_observation', js)
        self.assertIn('passive_capture', js)
        self.assertIn('visionRoutingVisualChangeThreshold', js)
        self.assertIn('visionRoutingVlmCooldownSec', js)
        self.assertIn('visionRoutingStableAfterChangeMs', js)
        self.assertIn('visionAnalyzerEnabled', js)
        self.assertIn('visionAnalyzerProvider', js)
        self.assertIn('visionAnalyzerBaseUrl', js)
        self.assertIn('visionAnalyzerModel', js)
        self.assertIn('visionAnalyzerApiKey', js)
        self.assertIn('visionAnalyzerApiKeyClear', js)
        self.assertIn('fetchVisionAnalyzerModelsBtn', js)
        self.assertIn('loadVisionAnalyzerModels', js)
        self.assertIn('/api/vision/models', js)
        self.assertIn('visionAnalyzerImageDetail', js)
        self.assertIn('visionAnalyzerMaxTextChars', js)
        self.assertIn('visionAnalyzerMaxObservations', js)
        self.assertIn('visionAnalyzerFallbackToRuntime', js)
        self.assertIn('evidence_count', js)
        self.assertIn('grounded', js)
        self.assertIn('last_route_decision', js)
        self.assertIn('capture_backend', js)
        self.assertIn('analyzer.last_status', js)
        self.assertIn('next.vision', js)
        self.assertIn('/api/vision/status', js)
        self.assertNotIn('next.chat.topic_history', js)
        self.assertNotIn('next.chat.long_term_memory', js)
        self.assertNotIn('config.chat?.long_term_memory', js)
        self.assertIn('next.chat.asr', js)
        self.assertNotIn('normalizeLongTermMemoryConfig', js)
        self.assertNotIn("router", html.lower())
        self.assertNotIn("memory", html.lower())
        self.assertNotIn("legacy", html.lower())
        self.assertNotIn("主 API", html)
        self.assertNotIn("副 API", html)
        self.assertNotIn("总结", html)
        self.assertIn('renderHermesRuntimeModelPresets', js)
        self.assertIn('renderHermesSessionPresets', js)
        self.assertIn('HERMES_INTERNAL_MODEL_PRESETS', js)
        self.assertNotIn('fetchRemoteModelsBtn', js)
        self.assertNotIn('fetchRouterModelsBtn', js)
        self.assertIn('populateMcpPresets(settingsPayload.mcp_server_presets)', js)
        self.assertIn('Object.entries(mcpServerPresets)', js)
        self.assertIn("Hermes MCP", html)
        self.assertIn("统一管理写入 Hermes 的 MCP 服务", html)
        self.assertIn("Hermes 技能", html)
        self.assertIn("导入并写入 Hermes", html)
        self.assertIn("创建并写入", html)
        self.assertIn('</section>\n\n      <section id="mcp"', html)
        self.assertIn("内建文件工具", js)
        self.assertIn("Hermes MCP 服务已写入", js)
        self.assertIn("本地 Hermes 技能已写入", js)
        self.assertIn('const isBuiltin = !!item.builtin || item.source_type === "builtin";', js)
        self.assertIn("内建文件工具会随运行时自动注册", js)


if __name__ == "__main__":
    unittest.main()
