from __future__ import annotations

import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INDEX_HTML = ROOT / "index.html"
SETTINGS_HTML = ROOT / "settings.html"
SETTINGS_JS = ROOT / "settings.js"


class ChatModesUiTests(unittest.TestCase):
    def test_index_contains_chat_mode_buttons_and_payload(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        self.assertIn('data-chat-mode="react"', source)
        self.assertIn('data-chat-mode="chat"', source)
        self.assertIn('data-chat-mode="skill"', source)
        self.assertIn("chat_mode: currentChatMode", source)
        self.assertIn("router_enabled: !!state.chat.router_enabled", source)
        self.assertIn('router_model: state.chat.router_model || ""', source)

    def test_index_contains_sidebar_buttons_in_new_order(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        settings_pos = source.find("<span>Settings</span>")
        history_pos = source.find("<span>Chat History</span>")
        new_chat_pos = source.find("<span>New Chat</span>")
        self.assertNotEqual(settings_pos, -1)
        self.assertNotEqual(history_pos, -1)
        self.assertNotEqual(new_chat_pos, -1)
        self.assertLess(settings_pos, history_pos)
        self.assertLess(history_pos, new_chat_pos)
        self.assertIn('id="nav-history"', source)
        self.assertIn('id="nav-chat"', source)

    def test_index_contains_topic_history_ui_and_api_hooks(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        self.assertIn('id="chat-history-drawer"', source)
        self.assertIn('id="chat-history-list"', source)
        self.assertIn('id="chat-history-refresh"', source)
        self.assertIn('/api/chat/topics', source)
        self.assertIn('async function createNewTopic', source)
        self.assertIn('async function loadTopicHistory', source)
        self.assertIn('async function selectTopic', source)
        self.assertIn('async function deleteTopic', source)
        self.assertIn('chat-history-delete', source)
        self.assertIn('pendingDeleteTopicId', source)
        self.assertIn('armPendingDeleteTopic', source)
        self.assertIn('clearPendingDeleteTopic', source)
        self.assertIn('\u786e\u8ba4\u5220\u9664', source)
        self.assertIn('chat-history-delete.is-danger', source)
        self.assertIn('deleteButton.textContent = isPendingDelete ? "\\u786e\\u8ba4\\u5220\\u9664" : "\\u5220\\u9664"', source)
        self.assertIn('deleteButton.setAttribute("aria-label", isPendingDelete ? "\\u786e\\u8ba4\\u5220\\u9664\\u8bdd\\u9898" : "\\u5220\\u9664\\u8bdd\\u9898")', source)
        self.assertNotIn('window.confirm', source)
        self.assertIn('method: "DELETE"', source)
        self.assertIn('/delete', source)
        self.assertIn('Method Not Allowed', source)
        self.assertIn('topic_history_enabled', source)
        self.assertIn('topic_id', source)
        self.assertIn('chat-asr-status', source)
        self.assertIn('function canStartPushToTalk', source)
        self.assertIn('startPushToTalk', source)
        self.assertIn('/api/asr/stream', source)
        self.assertIn('/api/health', source)
        self.assertIn('/api/asr/warmup', source)
        self.assertIn('state.chat?.asr?.api_base_url', source)
        self.assertIn('function candidateAsrBaseUrls()', source)
        self.assertIn('function buildAsrWarmupUrl(baseUrl = "")', source)
        self.assertIn('callQtBridge("startAsrWarmup")', source)
        self.assertIn('function isProbablyMacOS()', source)
        self.assertIn('[macOS] ASR 默认关闭，聊天仍可用', source)
        self.assertIn('function shouldRetryAsrAvailability(message)', source)
        self.assertIn('String(state.chat?.backend_url || "").trim()', source)
        self.assertIn('let sawSocketError = false;', source)
        self.assertIn('let lastSocketErrorMessage = "";', source)
        self.assertIn('lastSocketErrorMessage || (sawSocketError ? "ASR websocket error" : "ASR connection closed")', source)
        self.assertIn('while (token === asrRunToken && asrHotkeyPressed && !availability.ok) {', source)

    def test_index_tracks_thought_sessions_per_turn_boundary(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        self.assertIn('let activeThoughtSessionId = "";', source)
        self.assertIn('const approvalThoughtSessionRefs = new Map();', source)
        self.assertIn('const memorySuggestionRefs = new Map();', source)
        self.assertIn("function createThoughtSessionId()", source)
        self.assertIn("function beginThoughtSession(existingSessionId = \"\")", source)
        self.assertIn("function clearActiveThoughtSession(sessionId = \"\")", source)
        self.assertIn("function ensureThoughtGroup(round = 1, pending = false, sessionId = \"\")", source)
        self.assertIn("currentThoughtGroup.sessionId === normalizedSessionId", source)
        self.assertIn("const thoughtSessionId = beginThoughtSession();", source)
        self.assertIn("approvalThoughtSessionRefs.get(turnKey)", source)
        self.assertIn("await consumeChatStream(resp, { thoughtSessionId })", source)
        self.assertIn("clearActiveThoughtSession(thoughtSessionId);", source)

    def test_index_supports_searcher_role_and_step_batch_meta(self) -> None:
        source = INDEX_HTML.read_text(encoding="utf-8")
        self.assertIn('value === "searcher"', source)
        self.assertIn("function formatStepMeta(payload)", source)
        self.assertIn("Step ${stepIndex}", source)
        self.assertIn("Batch: ${batchSize} tool call", source)
        self.assertIn("const metaText = formatStepMeta(payload);", source)
        self.assertIn('memory_save_suggestion', source)
        self.assertIn('appendMemorySuggestionCard(payload, ensureFinalMessage)', source)
        self.assertIn('function normalizeMemorySuggestion(payload = {})', source)
        self.assertIn('function postMemoryDecision(topicId, action, candidate)', source)
        self.assertIn('/api/chat/memory/decision', source)
        self.assertIn('memory-suggestion', source)

    def test_settings_exposes_topic_history_controls_and_reasoning_input(self) -> None:
        html = SETTINGS_HTML.read_text(encoding="utf-8")
        js = SETTINGS_JS.read_text(encoding="utf-8")
        self.assertIn('id="chat-topic-history-enabled"', html)
        self.assertIn('id="chat-topic-history-summary-interval"', html)
        self.assertIn('id="chat-long-term-memory-enabled"', html)
        self.assertIn('id="chat-long-term-memory-project"', html)
        self.assertIn('id="chat-long-term-memory-read-enabled"', html)
        self.assertIn('id="chat-long-term-memory-ask-before-save"', html)
        self.assertIn('id="chat-asr-enabled"', html)
        self.assertIn('id="chat-asr-push-to-talk-key"', html)
        self.assertIn('id="chat-asr-interim-results"', html)
        self.assertIn('id="chat-max-reasoning-steps"', html)
        self.assertNotIn('max="12"', html)
        self.assertIn('chatTopicHistoryEnabled', js)
        self.assertIn('chatTopicHistorySummaryInterval', js)
        self.assertIn('chatLongTermMemoryEnabled', js)
        self.assertIn('chatLongTermMemoryProject', js)
        self.assertIn('chatLongTermMemoryReadEnabled', js)
        self.assertIn('chatLongTermMemoryAskBeforeSave', js)
        self.assertIn('chatAsrEnabled', js)
        self.assertIn('chatAsrPushToTalkKey', js)
        self.assertIn('chatAsrInterimResults', js)
        self.assertIn('next.chat.topic_history', js)
        self.assertIn('next.chat.long_term_memory', js)
        self.assertIn('config.chat?.long_term_memory', js)
        self.assertIn('next.chat.asr', js)
        self.assertIn('normalizeLongTermMemoryConfig', js)
        self.assertIn('populateMcpPresets(settingsPayload.mcp_server_presets)', js)
        self.assertIn('Object.entries(mcpServerPresets)', js)
        self.assertIn("MCP 工具与服务", html)
        self.assertIn("内建 file-tool 和第三方 MCP 服务", html)
        self.assertIn("内建 File Tool", js)
        self.assertIn('const isBuiltin = !!item.builtin || item.source_type === "builtin";', js)
        self.assertIn("内建 file-tool 会随运行时自动注册", js)


if __name__ == "__main__":
    unittest.main()
